logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://34.136.223.48:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://34.30.207.214:5000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq-5t2jnrnrca-uc.a.run.app
    port: 443
    ssl:
      enabled: true
