spring:
  data:
    mongodb:
      host: 34.135.193.104:27017
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
