spring:
  data:
    mongodb:
      host: auth-mongodb-5t2jnrnrca-uc.a.run.app
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
