eureka:
  instance:
    ip-address: 34.30.207.214
    non-secure-port: 5000

spring:
  data:
    mongodb:
      host: 34.135.193.104
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
